const constants = {
    //INVENTORY
    GET_INVENTORY_REQUEST: "GET_INVENTORY_REQUEST",
    GET_INVENTORY_SUCCESS: "GET_INVENTORY_SUCCESS",
    GET_INVENTORY_ERROR: "GET_INVENTORY_ERROR",

    //USER
    GET_LOGIN_REQUEST: "GET_LOGIN_REQUEST",
    GET_LOGIN_SUCCESS: "GET_LOGIN_SUCCESS",
    GET_LOGIN_ERROR: "GET_LOGIN_ERROR",
  
  };
  
  export default constants;
  